# Generated by Django 3.2.8 on 2021-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show1_month_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=20)),
            ],
        ),
    ]
